import Head from "next/head";
import SideBar from "@/components/SideBar";
import ContentMain from "@/components/Content";
export default function Home() {
  return (
    <>
      <Head>
        <title>UX Practise day 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-black flex">
        <SideBar />
        <ContentMain />
      </div>
    </>
  );
}
